//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UyumsoftProje2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALICI
    {
        public int aliciId { get; set; }
        public Nullable<int> uyeId { get; set; }
        public Nullable<int> siparisId { get; set; }
    
        public virtual SIPARIS SIPARIS { get; set; }
        public virtual UYE UYE { get; set; }
    }
}
