//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UyumsoftProje2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KITAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KITAP()
        {
            this.SATICI = new HashSet<SATICI>();
            this.SEPET = new HashSet<SEPET>();
            this.SEPET1 = new HashSet<SEPET>();
            this.STOK = new HashSet<STOK>();
        }
    
        public int kitapId { get; set; }
        public string kitapAdi { get; set; }
        public int sayfaSayisi { get; set; }
        public int fiyat { get; set; }
        public Nullable<int> kategoriId { get; set; }
        public Nullable<int> yayıneviId { get; set; }
        public Nullable<int> yazarId { get; set; }
        public string resim { get; set; }
        public Nullable<bool> durum { get; set; }
    
        public virtual KATEGORI KATEGORI { get; set; }
        public virtual YAYINEVI YAYINEVI { get; set; }
        public virtual YAZAR YAZAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SATICI> SATICI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEPET> SEPET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEPET> SEPET1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOK> STOK { get; set; }
    }
}
