//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UyumsoftProje2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALICI> ALICI { get; set; }
        public virtual DbSet<KATEGORI> KATEGORI { get; set; }
        public virtual DbSet<KITAP> KITAP { get; set; }
        public virtual DbSet<SATICI> SATICI { get; set; }
        public virtual DbSet<SEPET> SEPET { get; set; }
        public virtual DbSet<SIPARIS> SIPARIS { get; set; }
        public virtual DbSet<STOK> STOK { get; set; }
        public virtual DbSet<UYE> UYE { get; set; }
        public virtual DbSet<YAYINEVI> YAYINEVI { get; set; }
        public virtual DbSet<YAZAR> YAZAR { get; set; }
        public virtual DbSet<GOSTER> GOSTER { get; set; }
    
        public virtual ObjectResult<raporla_Result> raporla()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<raporla_Result>("raporla");
        }
    
        public virtual ObjectResult<S_RAPORLA2_Result> S_RAPORLA2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_RAPORLA2_Result>("S_RAPORLA2");
        }
    
        public virtual ObjectResult<SP_RAPORLA_Result> SP_RAPORLA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RAPORLA_Result>("SP_RAPORLA");
        }
    
        public virtual ObjectResult<SP_RAPORLA2_Result> SP_RAPORLA2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RAPORLA2_Result>("SP_RAPORLA2");
        }
    
        public virtual ObjectResult<SP_RAPORLA3_Result> SP_RAPORLA3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RAPORLA3_Result>("SP_RAPORLA3");
        }
    
        public virtual ObjectResult<SP_RAPORLA4_Result> SP_RAPORLA4()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RAPORLA4_Result>("SP_RAPORLA4");
        }
    
        public virtual ObjectResult<SP_GOSTER_Result> SP_GOSTER()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GOSTER_Result>("SP_GOSTER");
        }
    }
}
