//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UyumsoftProje2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEPET
    {
        public int sepetId { get; set; }
        public int adet { get; set; }
        public int tutar { get; set; }
        public Nullable<int> kitapId { get; set; }
        public Nullable<int> siparisId { get; set; }
        public Nullable<int> kullaniciId { get; set; }
    
        public virtual KITAP KITAP { get; set; }
        public virtual KITAP KITAP1 { get; set; }
        public virtual SIPARIS SIPARIS { get; set; }
        public virtual SIPARIS SIPARIS1 { get; set; }
        public virtual UYE UYE { get; set; }
    }
}
