//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UyumsoftProje2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK
    {
        public int stokId { get; set; }
        public int kalan { get; set; }
        public Nullable<int> kitapId { get; set; }
    
        public virtual KITAP KITAP { get; set; }
    }
}
